[package]
name = "wgrs"
version = "0.6.0"
authors = ["Jake McGinty <me@jake.su>"]
license = "GPL-3.0"
repository = "https://git.zx2c4.com/wireguard-rs/"
description = "Userspace implementation of WireGuard, a fast, modern and secure VPN tunnel."

[dependencies]
base64 = "^0.5"
blake2-rfc = "0.2"
byteorder = "^1.2"
bytes = "0.4"
daemonize = "0.2"
env_logger = "^0.4"
failure = "^0.1"
futures = "^0.1"
log = "^0.3"
hex = "^0.3"
rand = "^0.4"
libc = "0.2"
nix = "0.9"
rustc-serialize = "0.3.22"
pnet = "*"
snow = { git = "https://github.com/mcginty/snow", features = ["ring-accelerated"], branch = "wireguard" }
socket2 = "^0.3"
structopt = "^0.1"
structopt-derive = "^0.1"
time = "*"
tokio-io = "^0.1"
tokio-core = "^0.1"
tokio-uds = "^0.1"
tokio-utun = "^0.1"
tokio-timer = "^0.1"
treebitmap = "^0.2"
