[package]
name = "wireguard"
version = "0.1.0"
authors = ["The WireGuard developers", "Sascha Grunert <mail@saschagrunert.de>"]

[[bin]]
name = "userspace-wg"

[dependencies]
clap = { version = "2", features = ["yaml"] }
daemonize = "0"
libc = "0"
log = "0"
mowl = "1"
