[package]
name = "wgrs"
version = "0.6.0"
authors = ["Jake McGinty <me@jake.su>"]
license = "GPL-3.0"
repository = "https://git.zx2c4.com/wireguard-rs/"
description = "Userspace implementation of WireGuard, a fast, modern and secure VPN tunnel."

[lib]
name = "wireguard"
path = "src/lib.rs"

[[bin]]
name = "wgrs"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
build-binary = [ "daemonize", "structopt", "structopt-derive" ]

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "criterion"
harness = false

[dependencies]
base64 = "^0.5"
blake2-rfc = "0.2"
byteorder = "^1.2"
bytes = "0.4"
chacha20-poly1305-aead = "^0.1"
env_logger = "^0.4"
failure = "^0.1"
futures = "^0.1"
lazy_static = "^1"
log = "^0.3"
hex = "^0.3"
rand = "^0.4"
nix = "^0.10"
pnet = "*"
rust-crypto = "^0.2"
snow = { git = "https://github.com/mcginty/snow", features = ["ring-accelerated"], branch = "wireguard" }
socket2 = "^0.3"
subtle = "^0.5"
time = "^0.1"
tokio-io = "^0.1"
tokio-core = "^0.1"
tokio-uds = "^0.1"
tokio-utun = "^0.1"
tokio-timer = "^0.1"
treebitmap = "^0.2"
x25519-dalek = "^0.1"

daemonize = { version = "0.2", optional = true }
structopt = { version = "^0.1", optional = true }
structopt-derive = { version = "^0.1", optional = true }
