[package]
name = "wireguard"
version = "0.0.0"
authors = ["Jake McGinty <me@jake.su>"]
license = "GPL-3.0"
repository = "https://git.zx2c4.com/wireguard-rs/"
description = "Userspace implementation of WireGuard, a fast, modern and secure VPN tunnel."

[lib]
name = "wireguard"
path = "src/lib.rs"

[[bin]]
name = "wireguard-rs"
path = "src/main.rs"
required-features = ["binary"]

[features]
binary = [ "daemonize", "structopt", "structopt-derive", "fern", "chrono", "colored" ]

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "criterion"
harness = false

[dependencies]
base64 = "^0.5"
blake2-rfc = "0.2"
byteorder = "^1.2"
bytes = "0.4"
chacha20-poly1305-aead = "^0.1"
clear_on_drop = "^0.2"
derive_deref = "^1.0"
failure = "^0.1"
futures = "^0.1"
lazy_static = "^1"
log = "^0.4"
hex = "^0.3"
notify = "4.0.0"
rand = "^0.4"
nix = { git = "https://github.com/mcginty/nix", branch = "so_mark"} # TODO waiting on https://github.com/nix-rust/nix/pull/873
mio = "^0.6"
pnet_packet = "^0.20"
snow = { git = "https://github.com/mcginty/snow", features = ["ring-accelerated"], branch = "wireguard" }
socket2 = { version = "^0.3", features = ["reuseport"] }
subtle = "^0.5"
tokio-io = "^0.1"
tokio-core = "^0.1"
tokio-uds = "^0.1"
tokio-utun = "^0.1.10"
tokio-timer = "^0.1"
tokio-signal = "^0.1"
treebitmap = "^0.2"
x25519-dalek = "^0.1"

daemonize = { git = "https://github.com/mcginty/daemonize", optional = true }
chrono = { version = "^0.4", optional = true }
colored = { version = "^1.6", optional = true }
structopt = { version = "^0.1", optional = true }
structopt-derive = { version = "^0.1", optional = true }
fern = { version = "^0.5", features = ["colored"], optional = true }
